//! Built-in prompt pool derived from ShareGPT first-turns.
//!
//! Used as the default turn source when --turn is not specified, giving
//! realistic, cache-busting traffic across diverse topics and lengths.

use rand::SeedableRng;
use rand::rngs::SmallRng;
use rand::seq::IndexedRandom;

pub struct PromptSampler {
    rng: SmallRng,
    last: Option<usize>,
}

impl PromptSampler {
    pub fn new() -> Self {
        Self { rng: SmallRng::from_os_rng(), last: None }
    }

    /// Pick a prompt at random, avoiding an immediate repeat.
    pub fn next(&mut self) -> &'static str {
        let len = PROMPTS.len();
        loop {
            let idx = (0..len).collect::<Vec<_>>().choose(&mut self.rng).copied().unwrap_or(0);
            if Some(idx) != self.last {
                self.last = Some(idx);
                return PROMPTS[idx];
            }
        }
    }
}

pub static PROMPTS: &[&str] = &[
    // Coding
    "Write a Python function that finds all prime numbers up to n using the Sieve of Eratosthenes.",
    "Explain the difference between TCP and UDP with a practical example.",
    "How do I reverse a linked list in place in C++?",
    "Write a SQL query to find the top 5 customers by total order value.",
    "What is the difference between a process and a thread?",
    "Write a regex that matches valid email addresses.",
    "Implement a binary search algorithm in Rust.",
    "What are the SOLID principles and why do they matter?",
    "How does garbage collection work in Java?",
    "Write a bash script that monitors disk usage and emails an alert when it exceeds 80%.",
    "Explain how a hash table works, including collision handling strategies.",
    "What is the time complexity of quicksort in the average and worst case?",
    "Write a React component that fetches and displays a list of users from an API.",
    "How do I set up a Python virtual environment and why should I use one?",
    "Explain the difference between `==` and `===` in JavaScript.",
    "Write a Dockerfile for a Node.js application.",
    "What is a deadlock and how can it be prevented?",
    "How does async/await work under the hood in Python?",
    "Write a function to detect if a string is a palindrome.",
    "Explain the CAP theorem in distributed systems.",
    "How does the Linux kernel handle system calls?",
    "What is dependency injection and how does it improve testability?",
    "Write a Python script to parse a CSV file and compute column averages.",
    "How does HTTPS work? Explain the TLS handshake.",
    "What is the difference between REST and GraphQL?",
    "Implement a stack using two queues.",
    "What are Python decorators and how do you write one?",
    "How does Git's internal object model work?",
    "Write a function that detects cycles in a directed graph.",
    "What is memoization and when should you use it?",
    "How do database indexes work and what are the trade-offs?",
    "Write a WebSocket server in Python using asyncio.",
    "Explain the difference between horizontal and vertical scaling.",
    "What is a race condition? Give a concrete example.",
    "How do I implement rate limiting in an API?",
    "Write a merge sort implementation in Go.",
    "What is the difference between a mutex and a semaphore?",
    "How does Docker networking work?",
    "Explain the event loop in Node.js.",
    "Write a function to serialize and deserialize a binary tree.",

    // Writing & language
    "Write a cover letter for a software engineer applying to a fintech startup.",
    "Summarize the main arguments for and against universal basic income.",
    "Write a short story about a lighthouse keeper who discovers something unexpected.",
    "How do I improve the clarity and conciseness of my writing?",
    "Write a professional email declining a meeting invitation.",
    "Explain the difference between active and passive voice with examples.",
    "Write an introduction paragraph for an essay about climate change.",
    "What makes a great TED talk? Break down the key elements.",
    "Rewrite this sentence to be more formal: 'We gotta fix this ASAP or things will go south.'",
    "Write a product description for a pair of noise-cancelling headphones.",
    "What are the most common grammar mistakes in English writing?",
    "Write a persuasive argument for why cities should ban single-use plastics.",
    "How do I structure a technical blog post that developers will actually read?",
    "Write a haiku about debugging code at 2am.",
    "Explain the hero's journey narrative structure with a modern film example.",

    // Math & reasoning
    "Explain the Monty Hall problem and why switching doors increases your odds.",
    "What is Bayes' theorem and how is it used in spam filtering?",
    "Prove that there are infinitely many prime numbers.",
    "How do you calculate the probability of getting at least one six in four dice rolls?",
    "Explain what a derivative is intuitively, without using formulas first.",
    "What is the difference between correlation and causation? Give an example.",
    "How does public-key cryptography work mathematically?",
    "What is the birthday paradox and what is the probability for a group of 23 people?",
    "Explain gradient descent intuitively.",
    "What is Big O notation and why does it matter for software engineers?",
    "Solve: if a train leaves Chicago at 60 mph and another leaves New York at 80 mph, when do they meet?",
    "What is the difference between mean, median, and mode and when should you use each?",
    "Explain Euler's identity and why mathematicians find it beautiful.",
    "What is a Fourier transform and what is it used for?",
    "How does RSA encryption work step by step?",

    // Science & technology
    "How does a neural network learn? Explain backpropagation simply.",
    "What is the difference between supervised and unsupervised machine learning?",
    "Explain how CRISPR gene editing works.",
    "What causes a solar eclipse and how often does one occur?",
    "How does a lithium-ion battery work at the chemical level?",
    "What is quantum entanglement and does it allow faster-than-light communication?",
    "Explain the difference between RAM and storage, and why both matter.",
    "How do vaccines train the immune system?",
    "What is a black hole and what happens at the event horizon?",
    "Explain how GPS determines your location.",
    "What is the difference between fusion and fission?",
    "How does a computer processor execute machine instructions?",
    "What causes the northern lights?",
    "Explain how transformer models work at a high level.",
    "What is the difference between a virus and a bacterium?",
    "How does noise-cancelling technology work?",
    "What is CERN doing and why does it matter?",
    "Explain Moore's Law and whether it still holds today.",
    "How do recommendation systems like Netflix's work?",
    "What is the difference between IPv4 and IPv6?",

    // History & society
    "What were the main causes of World War I?",
    "Explain the significance of the Magna Carta.",
    "How did the printing press change European society?",
    "What was the Cold War and what ended it?",
    "Explain the differences between capitalism, socialism, and communism.",
    "What caused the 2008 financial crisis?",
    "How did the Roman Empire fall?",
    "What is the significance of the Marshall Plan?",
    "Explain the origins of the internet.",
    "What were the main drivers of the Industrial Revolution?",
    "How did colonialism shape modern Africa?",
    "What is the difference between a democracy and a republic?",
    "Explain the significance of the moon landing in 1969.",
    "What caused the Great Depression and how did it end?",
    "How did the Silk Road shape world trade and culture?",

    // Philosophy & ethics
    "What is the trolley problem and what does it reveal about ethics?",
    "Explain the difference between deontological and consequentialist ethics.",
    "What did Socrates mean by 'the unexamined life is not worth living'?",
    "Is free will compatible with determinism? Explain the main positions.",
    "What is Occam's razor and when should you apply it?",
    "Explain Plato's allegory of the cave.",
    "What are the ethical implications of artificial general intelligence?",
    "What is the ship of Theseus paradox?",
    "Should self-driving cars be programmed to minimize passenger or pedestrian harm in unavoidable crashes?",
    "What is existentialism and who are its key thinkers?",

    // Practical & everyday
    "What is the best way to negotiate a salary increase?",
    "How do I start investing with a small amount of money?",
    "What are the most effective study techniques backed by research?",
    "How does compound interest work and why does it matter for retirement?",
    "What are the key differences between renting and buying a home?",
    "How do I build a habit and make it stick?",
    "What should I know before starting my first business?",
    "How does sleep affect cognitive performance?",
    "What are the most evidence-based ways to reduce stress?",
    "How do I read a research paper effectively?",
    "What is the best way to give constructive feedback?",
    "How should I structure my day for maximum productivity?",
    "What is the difference between a will and a living trust?",
    "How do I evaluate whether a news article is reliable?",
    "What are the basics of personal finance I should know by 30?",

    // Data & analysis
    "What is the difference between a data warehouse and a data lake?",
    "Explain the ETL process and why it matters.",
    "How do I choose between a bar chart and a line chart?",
    "What is A/B testing and how do you design a valid experiment?",
    "Explain what p-value means in simple terms.",
    "What is overfitting in machine learning and how do you prevent it?",
    "How does k-means clustering work?",
    "What is the difference between precision and recall?",
    "How do I handle missing data in a dataset?",
    "What is a confusion matrix and how do I interpret it?",

    // Creative & fun
    "If you could have dinner with any three historical figures, who would you choose and why?",
    "Write a plot synopsis for a sci-fi novel where AI achieves consciousness inside a submarine.",
    "What would a city designed entirely around pedestrians and cyclists look like?",
    "Invent a new sport that combines chess and a physical activity.",
    "If the internet disappeared tomorrow, what would change most about daily life?",
    "Write a dialogue between Newton and Einstein discussing gravity.",
    "What would it take to terraform Mars for human habitation?",
    "Design a school curriculum optimized for the 21st century.",
    "If you could eliminate one human cognitive bias, which would have the most positive impact?",
    "What would global governance look like in 200 years?",

    // DevOps & infrastructure
    "Explain the difference between blue-green and canary deployments.",
    "How does Kubernetes decide where to schedule a pod?",
    "What is infrastructure as code and what are its main benefits?",
    "How do I design a CI/CD pipeline for a microservices application?",
    "What is the difference between a load balancer and an API gateway?",
    "Explain how Prometheus and Grafana work together for monitoring.",
    "What are the trade-offs between monolithic and microservices architecture?",
    "How does service mesh like Istio improve security in Kubernetes?",
    "What is chaos engineering and why do companies like Netflix use it?",
    "How do I estimate the cost of running a workload on AWS?",

    // Security
    "What is SQL injection and how do I prevent it?",
    "Explain how a man-in-the-middle attack works.",
    "What is the difference between authentication and authorization?",
    "How does OAuth 2.0 work?",
    "What is a zero-day vulnerability?",
    "Explain the principle of least privilege.",
    "How does a VPN protect your privacy?",
    "What is cross-site scripting (XSS) and how do I defend against it?",
    "What is the difference between symmetric and asymmetric encryption?",
    "How should I store passwords securely in a database?",

    // More coding
    "What is the difference between a shallow copy and a deep copy?",
    "Explain the observer design pattern with a real-world example.",
    "How do I implement a LRU cache in Python?",
    "What is tail recursion and why does it matter?",
    "Explain the difference between monomorphism and polymorphism.",
    "How does virtual memory work in modern operating systems?",
    "What is the difference between `let`, `const`, and `var` in JavaScript?",
    "How do I write a thread-safe singleton in Java?",
    "What is the difference between SQL and NoSQL databases?",
    "Explain how WebAssembly works and when you'd use it.",
    "How does Rust's ownership system prevent memory bugs?",
    "What is a bloom filter and what are its use cases?",
    "Explain the difference between eager and lazy evaluation.",
    "How do I profile a slow Python script?",
    "What is the actor model of concurrency?",
    "How does connection pooling work in databases?",
    "What is the difference between a compiler and an interpreter?",
    "Explain consistent hashing and why it's used in distributed systems.",
    "How do I implement pagination in a REST API?",
    "What are the trade-offs between SQL joins and denormalization?",
    "How does the JVM JIT compiler work?",
    "What is a context manager in Python and how do I write one?",
    "Explain the difference between optimistic and pessimistic locking.",
    "How do I write idiomatic Go error handling?",
    "What is a lambda function and when should I use one?",
    "Explain MapReduce with a simple example.",
    "How does protobuf compare to JSON for serialization?",
    "What is the difference between a monorepo and a polyrepo?",
    "How does rate limiting with a token bucket algorithm work?",
    "What is the difference between unit, integration, and end-to-end tests?",
    "How do I avoid N+1 query problems in an ORM?",
    "What is a state machine and where would you use one?",
    "Explain the difference between functional and object-oriented programming.",
    "How does a content delivery network work?",
    "What is tail call optimization?",
    "How do I use Docker Compose for local development?",
    "What is the difference between a webhook and polling?",
    "Explain event sourcing and CQRS.",
    "How does the Unix file permission model work?",
    "What is a trampoline function?",
    "How do I implement a simple publish-subscribe system?",
    "What is the difference between an abstract class and an interface?",

    // More writing
    "Write a resignation letter that is professional and leaves on good terms.",
    "How do I write a compelling executive summary?",
    "What is the difference between a metaphor and a simile? Give examples.",
    "Write a product launch announcement email for a new mobile app.",
    "How do I structure a five-paragraph essay?",
    "What makes dialogue in fiction feel authentic?",
    "Write a short bio for a conference speaker who specializes in machine learning.",
    "How do I write a post-mortem for a system outage?",
    "What is the inverted pyramid structure in journalism?",
    "Write a compelling job description for a senior backend engineer.",
    "How do I improve my technical writing for documentation?",
    "Write a LinkedIn recommendation for a colleague who is a strong team player.",
    "What is the difference between tone and voice in writing?",
    "How do I write a compelling abstract for a research paper?",
    "Write a short mystery story opening that hooks the reader immediately.",

    // More math & reasoning
    "What is P vs NP and why is it unsolved?",
    "Explain what an eigenvector is geometrically.",
    "How do you calculate compound interest with monthly contributions?",
    "What is a Markov chain and what can it model?",
    "Explain the central limit theorem in plain English.",
    "What is the difference between a permutation and a combination?",
    "How does linear regression work and what are its assumptions?",
    "What is entropy in information theory?",
    "Explain the concept of a limit in calculus intuitively.",
    "What is a p-norm and when would you use it in machine learning?",
    "How does principal component analysis reduce dimensionality?",
    "What is the law of large numbers?",
    "Explain how Simpson's paradox can mislead data analysis.",
    "What is the difference between interpolation and extrapolation?",
    "How does the expectation-maximization algorithm work?",

    // More science
    "How does the immune system distinguish self from non-self?",
    "Explain the difference between fission and fusion reactors.",
    "How do mRNA vaccines work?",
    "What is the Fermi paradox?",
    "Explain how LIDAR works in autonomous vehicles.",
    "What is the difference between a star and a planet?",
    "How does photosynthesis work at the molecular level?",
    "What causes the seasons on Earth?",
    "How do antibiotics work and why does resistance develop?",
    "What is dark matter and what evidence supports its existence?",
    "How does a transistor work?",
    "What is epigenetics?",
    "How does the ozone layer protect Earth?",
    "What is the difference between nuclear fission and radioactive decay?",
    "How do birds navigate during migration?",
    "What is a superconductor and why is it useful?",
    "How does sonar work?",
    "What is the difference between a hypothesis and a theory in science?",
    "How does CRISPR compare to older gene-editing techniques?",
    "What is the multiverse hypothesis?",

    // More history & society
    "What were the main causes of the French Revolution?",
    "How did the atomic bomb change international relations?",
    "What is the significance of the Bretton Woods agreement?",
    "How did the Renaissance emerge from the Middle Ages?",
    "What caused the fall of the Soviet Union?",
    "How did the slave trade shape the modern world economy?",
    "What was the Green Revolution and what were its consequences?",
    "Explain the difference between a parliamentary and a presidential system.",
    "What caused the Rwandan genocide and how was it stopped?",
    "How did Alexander the Great build his empire?",
    "What is the significance of the Turing test?",
    "How did social media change political discourse?",
    "What caused the 1970s oil crisis?",
    "How did the Black Death reshape European society?",
    "What is the significance of the Universal Declaration of Human Rights?",

    // More philosophy
    "What is Kant's categorical imperative?",
    "Explain the problem of induction.",
    "What is the difference between rationalism and empiricism?",
    "What did Nietzsche mean by the will to power?",
    "Is the scientific method itself falsifiable?",
    "What is the Chinese room argument against strong AI?",
    "Explain the difference between subjective and objective morality.",
    "What is consciousness and why is it philosophically hard to explain?",
    "What is epistemic humility and why does it matter?",
    "What is the difference between justice and fairness?",

    // More practical
    "How do I negotiate the price of a car?",
    "What is dollar-cost averaging and how does it work?",
    "How do I dispute an error on my credit report?",
    "What are the key things to check when reviewing a contract?",
    "How do I write a performance review for a direct report?",
    "What is the difference between a Roth IRA and a traditional IRA?",
    "How do I plan a project with uncertain scope?",
    "What is the best way to learn a new programming language?",
    "How do I give a technical presentation to a non-technical audience?",
    "What are the signs of burnout and how do you recover?",
    "How do I set up a budget that I'll actually stick to?",
    "What should I look for when evaluating a job offer beyond salary?",
    "How do I build a professional network as an introvert?",
    "What is the difference between a growth mindset and a fixed mindset?",
    "How do I run a productive team retrospective?",

    // More data & ML
    "What is the difference between bagging and boosting?",
    "How does a decision tree make predictions?",
    "Explain the vanishing gradient problem in deep learning.",
    "What is transfer learning and when should you use it?",
    "How does word2vec create word embeddings?",
    "What is the curse of dimensionality?",
    "Explain attention mechanisms in transformers.",
    "What is reinforcement learning and how does it differ from supervised learning?",
    "How do you evaluate a recommendation system?",
    "What is feature engineering and why does it matter?",
    "How does dropout regularization work?",
    "What is the difference between batch and stochastic gradient descent?",
    "What is RLHF and how is it used to train language models?",
    "How do you detect and fix data leakage in a model?",
    "What is the difference between a generative and a discriminative model?",

    // More DevOps
    "What is GitOps and how does it differ from traditional CI/CD?",
    "How does Terraform manage infrastructure state?",
    "What is the difference between horizontal pod autoscaling and vertical pod autoscaling?",
    "How do you do zero-downtime database migrations?",
    "What is eBPF and how is it used for observability?",
    "How do you implement secrets management in a Kubernetes cluster?",
    "What is the difference between a rolling update and a recreate deployment strategy?",
    "How does distributed tracing work with OpenTelemetry?",
    "What is a service level objective and how do you set one?",
    "How do you implement feature flags in a production system?",

    // More creative
    "Design an alien civilisation that communicates without language.",
    "What would a city on the ocean look like in 2150?",
    "Write a scene where two rival chefs compete in silence.",
    "If gravity were twice as strong, how would architecture change?",
    "Invent a holiday that celebrates a concept rather than an event.",
    "What would an economy without money look like?",
    "Write the opening paragraph of a thriller set entirely inside a data center.",
    "Design a board game about climate change negotiations.",
    "If you could add one sense to the human body, what would it be?",
    "Write a conversation between the first AI and the last human.",
];
